name: CustomItems
main: io.github.jaydy0102.CustomItems
version: 1.7.3
api-version: 1.20
commands:
  customitems:
    description: CustomItems admin command
    usage: /customitems reload
    permission: customitems.reload
permissions:
  customitems.reload:
    description: Reload plugin
    default: op
